version: '3'
services:
  jenkins:
    container_name: devjenkins
    image: jenkinsci/jenkins
    ports:
      - "8080:8080"
    volumes:
      - /home/docker/jenkins:/var/jenkins_home
    networks:
      - net
networks:
  net:
